version: "3.8"

services:
  web:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "1212:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./docs:/var/www/html:ro
    environment:
      SMTP_PASS: ${SMTP_PASS}
    restart: unless-stopped
